import React from 'react';
import { motion } from 'framer-motion';

interface LogoProps {
  theme?: 'light' | 'dark';
  showWordmark?: boolean;
  size?: number;
  interactive?: boolean;
}

// Icon container animations
const iconVariants = {
  hover: {
    scale: 1.05,
    rotate: [0, -5, 5, 0],
    transition: {
      duration: 0.5,
      ease: "easeInOut" as const,
    }
  }
};

export const Logo: React.FC<LogoProps> = ({
  theme = 'light',
  showWordmark = true,
  size = 40,
  interactive = true,
}) => {
  const isDark = theme === 'dark';

  return (
    <div className="flex items-center select-none">
      {showWordmark ? (
        <motion.div
          className="relative flex items-center cursor-pointer"
          style={{ height: size }}
          whileHover={interactive ? { scale: 1.05 } : undefined}
          transition={{ duration: 0.3 }}
        >
          <svg width="auto" height="100%" viewBox="0 0 400 80" fill="none" xmlns="http://www.w3.org/2000/svg" style={{ minWidth: size * 4.5 }}>
            <style>{`
              @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@800&display=swap');
              .logo-text-inline-full {
                font-family: 'Nunito', sans-serif;
                font-weight: 800;
              }
            `}</style>

            <rect x="0" y="0" width="80" height="80" rx="24" fill="url(#logoGradientFull)" />
            <text x="40" y="60" fill="#FFFFFF" fontSize="64" className="logo-text-inline-full" textAnchor="middle">S</text>

            {/* The main wordmark without the 'j' */}
            <text x="96" y="60" fill={isDark ? "#FFFFFF" : "#000000"} fontSize="60" className="logo-text-inline-full" letterSpacing="-1px">
              Sul<tspan fill="transparent">j</tspan>haoo
            </text>

            {/* The stem of the 'j' */}
            <text x="96" y="60" fill={isDark ? "#FFFFFF" : "#000000"} fontSize="60" className="logo-text-inline-full" letterSpacing="-1px" clipPath="url(#stemClipFull)">
              <tspan fill="transparent">Sul</tspan>j<tspan fill="transparent">haoo</tspan>
            </text>

            {/* The pink dot natively generated by the font */}
            <text x="96" y="60" fill="#FF1880" fontSize="60.3" className="logo-text-inline-full" letterSpacing="-1px" clipPath="url(#dotClipFull)">
              <tspan fill="transparent">Sul</tspan>j<tspan fill="transparent">haoo</tspan>
            </text>

            <defs>
              <clipPath id="stemClipFull">
                <rect x="0" y="27" width="400" height="60" />
              </clipPath>
              <clipPath id="dotClipFull">
                <rect x="0" y="0" width="400" height="27" />
              </clipPath>
              <linearGradient id="logoGradientFull" x1="0" y1="0" x2="80" y2="80" gradientUnits="userSpaceOnUse">
                <stop offset="0%" stopColor="#FF1880" />
                <stop offset="50%" stopColor="#B623CE" />
                <stop offset="100%" stopColor="#4B30F0" />
              </linearGradient>
            </defs>
          </svg>
        </motion.div>
      ) : (
        <motion.div
          className="relative flex items-center justify-center cursor-pointer"
          style={{ width: size, height: size }}
          whileHover={interactive ? "hover" : undefined}
          variants={interactive ? iconVariants : undefined}
        >
          <svg
            width="100%"
            height="100%"
            viewBox="0 0 80 80"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <style>{`
              @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@800&display=swap');
              .logo-text-inline {
                font-family: 'Nunito', sans-serif;
                font-weight: 800;
              }
            `}</style>
            <rect
              width="80"
              height="80"
              rx="24"
              fill="url(#logoGradientInline)"
            />
            <text x="40" y="60" fill="#FFFFFF" fontSize="64" className="logo-text-inline" textAnchor="middle">S</text>

            <defs>
              <linearGradient id="logoGradientInline" x1="0" y1="0" x2="80" y2="80" gradientUnits="userSpaceOnUse">
                <stop offset="0%" stopColor="#FF1880" />
                <stop offset="50%" stopColor="#B623CE" />
                <stop offset="100%" stopColor="#4B30F0" />
              </linearGradient>
            </defs>
          </svg>
        </motion.div>
      )}
    </div>
  );
};

export default Logo;
